### ISSUE TITLE
Method missing

### ISSUE THREAD

**Issue by ivan-leschinsky** [appodeal/slack_mailer#2]
https://github.com/appodeal/slack_mailer/blob/3c59e0a4ed781ab5c3f01d32e68c4dc9f72fea9b/lib/slack_mailer.rb#L20
Where is `mrandom` method?

**Comment by wwwermishel** [comment]
@ivan-leschinsky  That method was created in one of our rails project, and we don't moved that method to the gem. We fixed it.

**Comment by ivan-leschinsky** [comment]
You can just use `.sample` method on `slack_hook_urls` array. It is intended for getting random value from the array.
